### ISSUE TITLE
联动动画bug

### ISSUE THREAD

**Issue by OfficialYoungX** [GreenPomelo/qingyou-site-next#7]

**Comment by OfficialYoungX** [comment]
（手抖点错）测试发现，在safari里面 `useEffect` 只调用了一次。似乎导致，联动的动画全部失效。

**Comment by ChenKS12138** [comment]
Microsoft Edge也有这个问题，Chrome没有

**Comment by ChenKS12138** [comment]
https://github.com/GreenPomelo/qingyou-site-next/blob/5d69470f5273bb7f48df47d00e3380e3bdefe26b/src/App.js#L11-L22
在没次的滑动中，handleScroll 都有被触发，但是，setAfterScrollTop 和  setClientWidth 并没有成功更新afterScrollTop 和  clientWidth

**Comment by GooeyNyan** [comment]
准确地说不是没更新昂，是 scroll 这个值，写法上没兼容这些浏览器。

> [Google: document.documentelement.scrolltop safari](https://www.google.com/search?newwindow=1&ei=NOD1XInoGpWEoASNm4DYAw&q=document.documentelement.scrolltop+safari&oq=document.documentelement.scrolltop+&gs_l=psy-ab.1.1.35i39j0i20i263j0l3j0i203l3j0l2.3134.3359..4641...0.0..0.111.208.1j1......0....1..gws-wiz.stgX7Am-B0k)
>
> [document.body.scrollTop always returns 0 in Safari](https://github.com/nuxt/nuxt.js/issues/2512)
>
> [[document.documentElement.scrollTop return value differs in Chrome](https://stackoverflow.com/questions/20514596/document-documentelement-scrolltop-return-value-differs-in-chrome)](https://stackoverflow.com/questions/20514596/document-documentelement-scrolltop-return-value-differs-in-chrome)

**Comment by ChenKS12138** [comment]
这样子的啊，我试着改一下👀

**Comment by UZIhuhuhu** [comment]
#11 
这次 `PR` 中已经做了兼容
在[这次 commit](https://github.com/GreenPomelo/qingyou-site-next/pull/11/commits/76c807103e7b1d633083030d3a28d7ebcfb1e159) 中
